version: "3"
networks:
  calc_net:
    driver: bridge
services:

  flyway:
    image: flyway/flyway:8.5.5-alpine
    command: -url=jdbc:postgresql://pgsql:5432/habrdb -schemas=habrdb -user=habrkirill -password=qwerty -connectRetries=60 migrate
    volumes:
      - ./env/pgsql/migrations:/flyway/sql:ro
    depends_on:
      - pgsql
    networks:
      - calc_net

  server:
    image: server
    build: 
      context: .
      dockerfile: ./env/server/Dockerfile
    command: python ./server.py
    volumes:
      - ./apps:/apps
    ports:
      - "5000:5000"
    networks:
      - calc_net

  pgsql:
    image: postgres:13.3
    volumes:
      - ./calc-db-data:/var/lib/postgresql/data
      - ./env/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrkirill
      POSTGRES_PASSWORD: qwerty
      PG_DATA: /var/lib/postgresql/pgdata
    ports:
      - "43432:5432"
    networks:
      - calc_net
