version: "3"
networks:
  calc_net:
    driver: bridge
services:
  server:
    build: ./
    command: python ./server.py
    ports:
      - 5000:5000
  calc-pgsql:
    image: postgres:13.3
    volumes:
      - ./cmv-db-data:/var/lib/postgresql/data
      - ./env:/pgsql/initdb.sql/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrkirill
      POSTGRES_PASSWORD: qwerty
      PG_DATA: /var/lib/postgresql/pgdata
    ports:
      - 43432:5432
    networks:
      - calc_net
