version: "3"
networks:
  cmv_net:
    driver: bridge
services:
  server:
    build: ./
    command: python ./server.py
    ports:
      - 5000:5000
  cmv-pgsql:
    image: postgres:13.3
    volumes:
      - ./home/kirill/FitnessCalc/cmv-db-data:/var/lib/postgresql/data
      - ./home/kirill/FitnessCalc/env/pgsql/migrations/initdb.sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: habrdb
      POSTGRES_USER: habrkirill
      POSTGRES_PASSWORD: qwerty
      PG_DATA: /var/lib/postgresql/pgdata
    ports:
      - 43432:5432
    networks:
      - cmv_net
